plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
